runtime: nodejs12 # or nodejs10
handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# instance_class: F2

# service: "pharma-crm"

# env_variables:
#   BUCKET_NAME: "pharma-crm"

# handlers:
# - url: /static
#   static_dir: static

# - url: /index\.html
#   static_files: index.html
#   upload: index\.html

#   - url: /favicon\.ico
#   static_files: favicon.ico
#   upload: favicon\.ico

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
  
  
  